"""лента событий лота

Revision ID: 7410a50878e6
Revises: ac9b029e7e32
Create Date: 2026-09-02 15:54:08.945636

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7410a50878e6"
down_revision: str | Sequence[str] | None = "ac9b029e7e32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lot_events",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("by_machine", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_lot_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["lot_cards.id"],
            name=op.f("fk_lot_events_card_id_lot_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lot_events")),
    )
    op.create_index(op.f("ix_lot_events_card_id"), "lot_events", ["card_id"], unique=False)
    op.create_index(op.f("ix_lot_events_kind"), "lot_events", ["kind"], unique=False)
    op.create_index("lot_event_card_at", "lot_events", ["card_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("lot_event_card_at", table_name="lot_events")
    op.drop_index(op.f("ix_lot_events_kind"), table_name="lot_events")
    op.drop_index(op.f("ix_lot_events_card_id"), table_name="lot_events")
    op.drop_table("lot_events")
    # ### end Alembic commands ###
