"""Обсуждение строки рабочего списка

Revision ID: 083c7fb5fa6d
Revises: 49c6d222b7bf
Create Date: 2026-08-28 17:21:45.095647

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "083c7fb5fa6d"
down_revision: str | Sequence[str] | None = "49c6d222b7bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discussion_messages",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("row_id", sa.String(length=128), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_discussion_messages_author_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_discussion_messages_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discussion_messages")),
    )
    op.create_index(
        "discussion_module_row", "discussion_messages", ["module", "row_id"], unique=False
    )
    op.create_index(
        op.f("ix_discussion_messages_organization_id"),
        "discussion_messages",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_discussion_messages_organization_id"), table_name="discussion_messages")
    op.drop_index("discussion_module_row", table_name="discussion_messages")
    op.drop_table("discussion_messages")
    # ### end Alembic commands ###
