"""Номер закупки в карточке лота

Revision ID: ac9b029e7e32
Revises: 2504fce230b9
Create Date: 2026-09-01 17:51:40.069803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac9b029e7e32"
down_revision: str | Sequence[str] | None = "2504fce230b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Значение по умолчанию — только на время заливки: `NOT NULL` не добавить
    # к таблице, где уже есть строки. В схеме его не оставляем, номер
    # проставляет заведение карточки.
    op.add_column(
        "lot_cards",
        sa.Column("source_number", sa.String(length=64), nullable=False, server_default=""),
    )
    op.alter_column("lot_cards", "source_number", server_default=None)
    op.create_index(
        op.f("ix_lot_cards_source_number"), "lot_cards", ["source_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lot_cards_source_number"), table_name="lot_cards")
    op.drop_column("lot_cards", "source_number")
    # ### end Alembic commands ###
