"""Лот в работе между отделами

Revision ID: 93cff7dbcd56
Revises: 7aba259e9c55
Create Date: 2026-08-25 17:05:07.118828

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93cff7dbcd56"
down_revision: str | Sequence[str] | None = "7aba259e9c55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tender_works",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("customer", sa.String(length=255), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "ANALYSIS", "SUPPLY", "RETURNED", name="workstage", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("analysis_note", sa.Text(), nullable=False),
        sa.Column("supply_note", sa.Text(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tender_works_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tender_works_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tender_works")),
    )
    op.create_index(op.f("ix_tender_works_code"), "tender_works", ["code"], unique=False)
    op.create_index(
        op.f("ix_tender_works_organization_id"), "tender_works", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_tender_works_stage"), "tender_works", ["stage"], unique=False)
    op.create_table(
        "tender_work_positions",
        sa.Column("work_id", sa.Uuid(), nullable=False),
        sa.Column("folder_path", sa.String(length=1024), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("ordering", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["work_id"],
            ["tender_works.id"],
            name=op.f("fk_tender_work_positions_work_id_tender_works"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tender_work_positions")),
    )
    op.create_index(
        op.f("ix_tender_work_positions_work_id"), "tender_work_positions", ["work_id"], unique=False
    )
    op.create_table(
        "tender_work_options",
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("FOUND", "ASKED", "SUPPLY", name="optionsource", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("supplier", sa.String(length=255), nullable=False),
        sa.Column("marketplace", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("delivery_days", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["tender_work_positions.id"],
            name=op.f("fk_tender_work_options_position_id_tender_work_positions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_tender_work_options_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tender_work_options")),
    )
    op.create_index(
        op.f("ix_tender_work_options_position_id"),
        "tender_work_options",
        ["position_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tender_work_options_position_id"), table_name="tender_work_options")
    op.drop_table("tender_work_options")
    op.drop_index(op.f("ix_tender_work_positions_work_id"), table_name="tender_work_positions")
    op.drop_table("tender_work_positions")
    op.drop_index(op.f("ix_tender_works_stage"), table_name="tender_works")
    op.drop_index(op.f("ix_tender_works_organization_id"), table_name="tender_works")
    op.drop_index(op.f("ix_tender_works_code"), table_name="tender_works")
    op.drop_table("tender_works")
    # ### end Alembic commands ###
