"""Техническое задание позиции в работе

Revision ID: bbd1ffa9e854
Revises: c4710d2220e7
Create Date: 2026-08-26 10:50:30.874560

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbd1ffa9e854"
down_revision: str | Sequence[str] | None = "c4710d2220e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tender_work_positions", sa.Column("spec", sa.Text(), server_default="", nullable=False)
    )
    op.add_column(
        "tender_work_positions",
        sa.Column("spec_source", sa.String(length=512), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tender_work_positions", "spec_source")
    op.drop_column("tender_work_positions", "spec")
    # ### end Alembic commands ###
