"""Карточка лота, задачи и согласование

Revision ID: 12de75d0bd0b
Revises: e2b65b7bbaac
Create Date: 2026-09-01 16:22:25.854002

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12de75d0bd0b"
down_revision: str | Sequence[str] | None = "e2b65b7bbaac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lot_cards",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("row_id", sa.String(length=128), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("customer", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("enstru_code", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "DISCUSSION",
                "ANALYSIS",
                "APPROVAL",
                "READY",
                "AWAITING",
                "WON",
                "LOST",
                "CONTRACT",
                "FULFILLING",
                "AWAITING_PAYMENT",
                "DONE",
                "SKIPPED",
                "CANCELLED",
                name="lotstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "participation",
            sa.Enum("MAYBE", "YES", "NO", name="participation", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("skip_reason", sa.Text(), nullable=False),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("won_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("winner", sa.Text(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
            name=op.f("fk_lot_cards_manager_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_lot_cards_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_lot_cards_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lot_cards")),
        sa.UniqueConstraint("module", "row_id", name="card_on_row"),
    )
    op.create_index("card_deadline", "lot_cards", ["deadline"], unique=False)
    op.create_index("card_owner", "lot_cards", ["owner_id", "status"], unique=False)
    op.create_index("card_status", "lot_cards", ["organization_id", "status"], unique=False)
    op.create_index(op.f("ix_lot_cards_category"), "lot_cards", ["category"], unique=False)
    op.create_index(op.f("ix_lot_cards_code"), "lot_cards", ["code"], unique=False)
    op.create_index(op.f("ix_lot_cards_enstru_code"), "lot_cards", ["enstru_code"], unique=False)
    op.create_index(op.f("ix_lot_cards_manager_id"), "lot_cards", ["manager_id"], unique=False)
    op.create_index(
        op.f("ix_lot_cards_organization_id"), "lot_cards", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_lot_cards_owner_id"), "lot_cards", ["owner_id"], unique=False)
    op.create_index(op.f("ix_lot_cards_status"), "lot_cards", ["status"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "MANAGER",
                "SUPPLY",
                "LEGAL",
                "TECHNOLOGIST",
                "ASSEMBLER",
                name="approvalkind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "WAITING",
                "APPROVED",
                "REJECTED",
                name="approvalstate",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("by_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["by_id"], ["users.id"], name=op.f("fk_approvals_by_id_users"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["lot_cards.id"],
            name=op.f("fk_approvals_card_id_lot_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("card_id", "kind", name="approval_once"),
    )
    op.create_index(op.f("ix_approvals_card_id"), "approvals", ["card_id"], unique=False)
    op.create_table(
        "lot_files",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("added_by_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["added_by_id"],
            ["users.id"],
            name=op.f("fk_lot_files_added_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["lot_cards.id"],
            name=op.f("fk_lot_files_card_id_lot_cards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["files.id"], name=op.f("fk_lot_files_file_id_files"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lot_files")),
    )
    op.create_index(op.f("ix_lot_files_card_id"), "lot_files", ["card_id"], unique=False)
    op.create_index(op.f("ix_lot_files_file_id"), "lot_files", ["file_id"], unique=False)
    op.create_index("lot_file_card", "lot_files", ["card_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column(
            "department",
            sa.Enum(
                "DISCUSSION",
                "ANALYSIS",
                "SUPPLY",
                "LEGAL",
                "APPROVAL",
                "SUBMISSION",
                name="department",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "state",
            sa.Enum("OPEN", "DONE", "CANCELLED", name="taskstate", native_enum=False, length=12),
            nullable=False,
        ),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_tasks_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["lot_cards.id"],
            name=op.f("fk_tasks_card_id_lot_cards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tasks_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tasks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index(op.f("ix_tasks_card_id"), "tasks", ["card_id"], unique=False)
    op.create_index(op.f("ix_tasks_department"), "tasks", ["department"], unique=False)
    op.create_index(op.f("ix_tasks_organization_id"), "tasks", ["organization_id"], unique=False)
    op.create_index(op.f("ix_tasks_state"), "tasks", ["state"], unique=False)
    op.create_index("task_assignee", "tasks", ["assignee_id", "state"], unique=False)
    op.create_index(
        "task_department", "tasks", ["organization_id", "department", "state"], unique=False
    )
    op.create_index("task_due", "tasks", ["due_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("task_due", table_name="tasks")
    op.drop_index("task_department", table_name="tasks")
    op.drop_index("task_assignee", table_name="tasks")
    op.drop_index(op.f("ix_tasks_state"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_organization_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_department"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_card_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("lot_file_card", table_name="lot_files")
    op.drop_index(op.f("ix_lot_files_file_id"), table_name="lot_files")
    op.drop_index(op.f("ix_lot_files_card_id"), table_name="lot_files")
    op.drop_table("lot_files")
    op.drop_index(op.f("ix_approvals_card_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_lot_cards_status"), table_name="lot_cards")
    op.drop_index(op.f("ix_lot_cards_owner_id"), table_name="lot_cards")
    op.drop_index(op.f("ix_lot_cards_organization_id"), table_name="lot_cards")
    op.drop_index(op.f("ix_lot_cards_manager_id"), table_name="lot_cards")
    op.drop_index(op.f("ix_lot_cards_enstru_code"), table_name="lot_cards")
    op.drop_index(op.f("ix_lot_cards_code"), table_name="lot_cards")
    op.drop_index(op.f("ix_lot_cards_category"), table_name="lot_cards")
    op.drop_index("card_status", table_name="lot_cards")
    op.drop_index("card_owner", table_name="lot_cards")
    op.drop_index("card_deadline", table_name="lot_cards")
    op.drop_table("lot_cards")
    # ### end Alembic commands ###
