"""Заметка снабжения по позиции

Revision ID: 49c6d222b7bf
Revises: bbd1ffa9e854
Create Date: 2026-08-26 11:58:14.227602

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49c6d222b7bf"
down_revision: str | Sequence[str] | None = "bbd1ffa9e854"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tender_work_positions",
        sa.Column("note", sa.String(length=500), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tender_work_positions", "note")
    # ### end Alembic commands ###
