"""Подтверждённый вариант закупки

Revision ID: c4710d2220e7
Revises: 93cff7dbcd56
Create Date: 2026-08-25 17:12:08.516421

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4710d2220e7"
down_revision: str | Sequence[str] | None = "93cff7dbcd56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tender_work_options",
        sa.Column("chosen", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tender_work_options", "chosen")
    # ### end Alembic commands ###
