"""Закупки и их файлы

Revision ID: 8d59d2f7828e
Revises: b5f09baa2c57
Create Date: 2026-08-05 14:46:34.907115

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d59d2f7828e"
down_revision: str | Sequence[str] | None = "b5f09baa2c57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tender_cases",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("customer", sa.String(length=512), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "READY",
                "ANALYZING",
                "ANALYZED",
                "ARCHIVED",
                name="casestatus",
                native_enum=False,
                length=32,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_tender_cases_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tender_cases_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tender_cases")),
    )
    op.create_index(
        "ix_tender_cases_org_created",
        "tender_cases",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tender_cases_organization_id"), "tender_cases", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_tender_cases_status"), "tender_cases", ["status"], unique=False)
    op.create_table(
        "tender_case_files",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("relative_path", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["tender_cases.id"],
            name=op.f("fk_tender_case_files_case_id_tender_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_tender_case_files_file_id_files"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tender_case_files")),
        sa.UniqueConstraint("case_id", "relative_path", name="case_relative_path"),
    )
    op.create_index(
        op.f("ix_tender_case_files_case_id"), "tender_case_files", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_tender_case_files_file_id"), "tender_case_files", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_tender_case_files_sha256"), "tender_case_files", ["sha256"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tender_case_files_sha256"), table_name="tender_case_files")
    op.drop_index(op.f("ix_tender_case_files_file_id"), table_name="tender_case_files")
    op.drop_index(op.f("ix_tender_case_files_case_id"), table_name="tender_case_files")
    op.drop_table("tender_case_files")
    op.drop_index(op.f("ix_tender_cases_status"), table_name="tender_cases")
    op.drop_index(op.f("ix_tender_cases_organization_id"), table_name="tender_cases")
    op.drop_index("ix_tender_cases_org_created", table_name="tender_cases")
    op.drop_table("tender_cases")
    # ### end Alembic commands ###
