"""Категория товара в обсуждении

Revision ID: 2504fce230b9
Revises: 12de75d0bd0b
Create Date: 2026-09-01 17:03:23.351747

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2504fce230b9"
down_revision: str | Sequence[str] | None = "12de75d0bd0b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Значение по умолчанию — только на время заливки. Без него `NOT NULL` не
    # добавить к таблице, в которой уже есть строки; оставлять его в схеме
    # незачем, категорию проставляет заведение обсуждения.
    op.add_column(
        "discussions",
        sa.Column("category", sa.String(length=128), nullable=False, server_default=""),
    )
    op.alter_column("discussions", "category", server_default=None)
    op.create_index(op.f("ix_discussions_category"), "discussions", ["category"], unique=False)
    op.create_index(
        op.f("ix_discussions_enstru_code"), "discussions", ["enstru_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_discussions_enstru_code"), table_name="discussions")
    op.drop_index(op.f("ix_discussions_category"), table_name="discussions")
    op.drop_column("discussions", "category")
    # ### end Alembic commands ###
