"""Обсуждение закупки

Revision ID: e2b65b7bbaac
Revises: 083c7fb5fa6d
Create Date: 2026-09-01 10:21:56.748546

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2b65b7bbaac"
down_revision: str | Sequence[str] | None = "083c7fb5fa6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discussions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("row_id", sa.String(length=128), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("customer", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("enstru_code", sa.String(length=32), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "DRAFTING",
                "MODERATION",
                "WITH_LAWYERS",
                "SENT",
                "NOT_NEEDED",
                name="discussionstage",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "WAITING",
                "ACCEPTED",
                "REJECTED",
                "CLOSED",
                "COMPLAINT",
                name="discussionoutcome",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "writing",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "READY",
                "FAILED",
                name="discussionwriting",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("trouble", sa.Text(), nullable=False),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("ai_text", sa.Text(), nullable=False),
        sa.Column("ai_model", sa.String(length=64), nullable=False),
        sa.Column("ai_written_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("edited_by_id", sa.Uuid(), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
            name=op.f("fk_discussions_assignee_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["edited_by_id"],
            ["users.id"],
            name=op.f("fk_discussions_edited_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_discussions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discussions")),
        sa.UniqueConstraint("module", "row_id", name="discussion_on_row"),
    )
    op.create_index("discussion_deadline", "discussions", ["deadline"], unique=False)
    op.create_index("discussion_stage", "discussions", ["module", "stage"], unique=False)
    op.create_index(
        op.f("ix_discussions_assignee_id"), "discussions", ["assignee_id"], unique=False
    )
    op.create_index(
        op.f("ix_discussions_organization_id"), "discussions", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_discussions_stage"), "discussions", ["stage"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_discussions_stage"), table_name="discussions")
    op.drop_index(op.f("ix_discussions_organization_id"), table_name="discussions")
    op.drop_index(op.f("ix_discussions_assignee_id"), table_name="discussions")
    op.drop_index("discussion_stage", table_name="discussions")
    op.drop_index("discussion_deadline", table_name="discussions")
    op.drop_table("discussions")
    # ### end Alembic commands ###
