"""Постоянный код строки

Revision ID: 7aba259e9c55
Revises: 6a542fef3a59
Create Date: 2026-08-24 12:40:49.778349

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aba259e9c55"
down_revision: str | Sequence[str] | None = "6a542fef3a59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worklist_codes",
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("row_key", sa.String(length=64), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worklist_codes")),
        sa.UniqueConstraint("module", "number", name="module_number"),
        sa.UniqueConstraint("module", "row_key", name="module_row"),
    )
    op.create_index(op.f("ix_worklist_codes_module"), "worklist_codes", ["module"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_worklist_codes_module"), table_name="worklist_codes")
    op.drop_table("worklist_codes")
    # ### end Alembic commands ###
