"""переходы в ленте событий

Revision ID: e04bd4172a35
Revises: 7410a50878e6
Create Date: 2026-09-02 16:19:21.453884

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e04bd4172a35"
down_revision: str | Sequence[str] | None = "7410a50878e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lot_events", sa.Column("from_status", sa.String(length=32), nullable=False))
    op.add_column("lot_events", sa.Column("to_status", sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lot_events", "to_status")
    op.drop_column("lot_events", "from_status")
    # ### end Alembic commands ###
